/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stockmanagement;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sahil
 */
public class search_bill extends javax.swing.JInternalFrame implements myvariables
{

    /**
     * Creates new form bank_business_details
     */
    public search_bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Shop Search");
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Search Bill");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Bill No", "Category", "Subcategory", "Company", "Model", "Quantity", "Amount"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(1200, 100));
        jTable1.setPreferredSize(new java.awt.Dimension(1200, 300));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("From Date : -");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Total Amount : -");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("To Date : -");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bill No : -");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("|");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(280, 280, 280)
                                .addComponent(jButton2)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(237, 237, 237))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jDateChooser1.getDate()== null || jDateChooser2.getDate() == null)
        {
            JOptionPane.showMessageDialog(rootPane,"Please select Dates .");
        }
        else
        {
            try
            {
                Connection myconnection;
                myconnection = DriverManager.getConnection(path+place,username,password);
                
                try
                {
                    String q = "select * from business_table where date between ? and ?";
                    
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                    String cdate = myformat.format(jDateChooser1.getDate());
                    String cdate2 = myformat.format(jDateChooser2.getDate());
                    
                    mystatement.setString(1,cdate);
                    mystatement.setString(2,cdate2);
                    
                    ResultSet myresult = mystatement.executeQuery();
               
                    DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                    mymodel.setRowCount(0);
   
                
                        if(myresult.next())
                        {
                            do
                            {
                                
                                String date = myresult.getString("date");
                                String cat[] = myresult.getString("category").split(",");
                                String subcat[] = myresult.getString("subcategory").split(",");
                                String comp[] = myresult.getString("company").split(",");
                                String model[] = myresult.getString("model").split(",");
                                 String qnt[] = myresult.getString("quantity").split(",");
                                String price[] = myresult.getString("price").split(",");
                                String t_amt = myresult.getString("total_amt");
                                jTextField1.setText(t_amt);
                                for(int i=0 ; i<cat.length ; i++)
                                {
                                 mymodel.addRow(new Object[] {date,cat[i],subcat[i],comp[i],model[i],qnt[i],price[i]});
                                }
                            }
                            while(myresult.next());
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane,"No Records Found .");
                        }
                        
                        
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
            }
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
            try
            {
                Connection myconnection;
                myconnection = DriverManager.getConnection(path+place,username,password);
                
                try
                {
                    String q = "select * from business_table";
                    
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                   
                    ResultSet myresult = mystatement.executeQuery();
               
                    DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                    mymodel.setRowCount(0);
                    String t_amt="";
                    
                    if(myresult.next())
                        {
                            do
                            {
                                
                                String date = myresult.getString("date");
                                String bill = myresult.getString("bill_no");
                                String cat[] = myresult.getString("category").split(",");
                                String subcat[] = myresult.getString("subcategory").split(",");
                                String comp[] = myresult.getString("company").split(",");
                                String model[] = myresult.getString("model").split(",");
                                String qnt[] = myresult.getString("quantity").split(",");
                                
                                
                                String price[] = myresult.getString("price").split(",");
                                
                                 t_amt += myresult.getString("total_amt");
                                
                                jTextField1.setText(t_amt);
                                
                                for(int i=0 ; i< cat.length ; i++)
                                {
                                 mymodel.addRow(new Object[] {date,bill,cat[i],subcat[i],comp[i],model[i],qnt[i],price[i]});
                                }
                            }
                            while(myresult.next());
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane,"No Records Found .");
                        }
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
            }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         
        if(jTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter Bill No .");
        }
        else
        {
            try
            {
                Connection myconnection;
                myconnection = DriverManager.getConnection(path+place,username,password);
                
                try
                {
                    String q = "select * from business_table where bill_no = ?";
                    
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    
                    
                    mystatement.setString(1,jTextField2.getText());
                    
                    ResultSet myresult = mystatement.executeQuery();
               
                    DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                    mymodel.setRowCount(0);
   
                
                        if(myresult.next())
                        {
                            do
                            {
                                
                                String date = myresult.getString("date");
                                String bill = myresult.getString("bill_no");
                                String cat[] = myresult.getString("category").split(",");
                                String subcat[] = myresult.getString("subcategory").split(",");
                                String comp[] = myresult.getString("company").split(",");
                                String model[] = myresult.getString("model").split(",");
                                 String qnt[] = myresult.getString("quantity").split(",");
                                String price[] = myresult.getString("price").split(",");
                                String t_amt = myresult.getString("total_amt");
                                
                                jTextField1.setText(t_amt);
                                
                                for(int i=0 ; i<cat.length ; i++)
                                {
                                 mymodel.addRow(new Object[] {date,bill,cat[i],subcat[i],comp[i],model[i],qnt[i],price[i]});
                                }
                            }
                            while(myresult.next());
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane,"No Records Found .");
                        }
                        
                        
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
            }
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
